# Generated by Django 5.2.14 on 2026-05-31 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_tc', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cuisines',
                'db_table': 'restaurant_cuisine',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_tc', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(choices=[('HK', 'Hong Kong Island'), ('KLN', 'Kowloon'), ('NT', 'New Territories'), ('Macau', 'Macau')], max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'restaurant_district',
                'ordering': ['region', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_tc', models.CharField(blank=True, max_length=100)),
                ('tag_type', models.CharField(choices=[('dietary', 'Dietary'), ('amenity', 'Amenity'), ('atmosphere', 'Atmosphere'), ('meal', 'Meal Type')], max_length=20)),
            ],
            options={
                'db_table': 'restaurant_tag',
                'ordering': ['tag_type', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_tc', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('address_en', models.TextField()),
                ('address_tc', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('price_range', models.CharField(choices=[('$', 'Under $50'), ('$$', '$50-100'), ('$$$', '$100-200'), ('$$$$', '$200-500'), ('$$$$$', '$500+')], default='$$', max_length=5)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('claimed', 'Claimed by Owner'), ('closed', 'Permanently Closed')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_restaurants', to=settings.AUTH_USER_MODEL)),
                ('cuisines', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.cuisine')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='restaurants.district')),
                ('tags', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.tag')),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ['-avg_rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_photo',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_tc', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('side', 'Side'), ('special', 'Chef Special')], default='main', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
                ('dietary_tags', models.ManyToManyField(blank=True, related_name='menu_items', to='restaurants.tag')),
            ],
            options={
                'db_table': 'menu_item',
                'ordering': ['category', 'name_en'],
            },
        ),
    ]
