# Generated by Django 5.2.14 on 2026-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='External photo URL'),
        ),
    ]
