# Generated by Django 5.2.14 on 2026-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_zh', models.CharField(blank=True, max_length=200)),
                ('cuisine_type', models.CharField(choices=[('chinese', 'Chinese'), ('western', 'Western'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indian', 'Indian'), ('italian', 'Italian'), ('french', 'French'), ('fusion', 'Fusion'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('fast_food', 'Fast Food'), ('seafood', 'Seafood'), ('other', 'Other')], default='other', max_length=20)),
                ('price_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Fine Dining')], default='$$', max_length=4)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ['name_en'],
            },
        ),
    ]
