# Generated by Django 5.2.14 on 2026-05-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deal_type', models.CharField(choices=[('discount', 'Discount'), ('set_menu', 'Set Menu'), ('free_item', 'Free Item'), ('cashback', 'Cashback'), ('happy_hour', 'Happy Hour')], max_length=20)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('terms', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'deal',
                'ordering': ['-start_date'],
            },
        ),
    ]
